[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "quantgauge"
version = "0.1.7"
description = "Quantitative finance library with C++ backends"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Kabinan", email = "bkabinan@gmail.com"}
]
dependencies = [
    "numpy",
    "scipy",
    "pytest",
    "matplotlib"

]

[tool.scikit-build]
cmake.version = ">=3.15"
wheel.install-dir = "quantgauge"

[tool.scikit-build.sdist]
# We must include the build configuration files explicitly
include = [
    "pyproject.toml",
    "CMakeLists.txt",
    "README.md",
    "quantgauge/**"
]